# Generated by Django 5.2.14 on 2026-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.CharField(db_index=True, max_length=64)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=16)),
                ('rack_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=3, max_digits=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_geocoded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'indexes': [models.Index(fields=['state'], name='fuelstation_state_idx'), models.Index(fields=['retail_price'], name='fuelstation_price_idx'), models.Index(fields=['city'], name='fuelstation_city_idx'), models.Index(fields=['opis_truckstop_id'], name='fuelstation_opis_idx'), models.Index(fields=['rack_id'], name='fuelstation_rack_idx')],
            },
        ),
    ]
